# Server
server.port=8080

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/citizen_grievance_portal
spring.datasource.username=root
spring.datasource.password=prerna@31

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html